using System;
using UnityEngine;
using Sirenix.OdinInspector;


public class Player : MonoBehaviour{
    [HideInInspector] public PlayerControls controls;
    [HideInInspector] public PlayerMovement movement;
    [HideInInspector] public new PlayerCamera camera;

    void Awake(){
        controls = GetComponent<PlayerControls>();
        movement = GetComponent<PlayerMovement>();
    }

    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
